# Generated by Django 4.2 on 2023-04-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pallets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField()),
                ('price', models.FloatField(unique=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
