help:
	django-admin --help


mig:
	python3 manage.py makemigrations
	python3 manage.py migrate


ma:
	python3 manage.py makemigrations

mi:
	python3 manage.py migrate

run:
	python3 manage.py runserver
