# Generated by Django 4.2.1 on 2023-05-22 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_brand_alter_aboutus_image_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
