# Generated by Django 4.1.7 on 2023-03-31 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vopros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('date', models.DateTimeField(null=True, verbose_name='Date publish')),
            ],
        ),
        migrations.CreateModel(
            name='Otvet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('votes', models.IntegerField(default=0)),
                ('is_true', models.BooleanField(default=False)),
                ('vopros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.vopros')),
            ],
        ),
    ]
